// src/web-components/IterationDeckToolbar.ts
import { LitElement, html, css, unsafeCSS } from 'lit'
import { customElement, state } from 'lit/decorators.js'
import { getIterationDeckStore, isDevelopment, type DeckData } from './store.js'
import { spacing, colors, typography, components, zIndex } from '../tokens.js'

@customElement('iteration-deck-toolbar')
export class IterationDeckToolbar extends LitElement {
  @state() private decks: DeckData[] = []
  @state() private activeDeckId: string | null = null
  @state() private isVisible = false

  private store = getIterationDeckStore()

  static styles = css`
    :host {
      position: fixed;
      bottom: ${unsafeCSS(spacing.xl)};
      left: 50%;
      transform: translateX(-50%);
      z-index: ${unsafeCSS(zIndex.toolbar)};
      font-family: ${unsafeCSS(typography.fontFamily)};
      font-size: ${unsafeCSS(typography.fontSize.sm)};
    }

    .toolbar {
      display: flex;
      align-items: center;
      gap: ${unsafeCSS(spacing.sm)};
      background: ${unsafeCSS(colors.background.overlay)};
      backdrop-filter: ${unsafeCSS(components.toolbar.backdropFilter)};
      border: 1px solid ${unsafeCSS(colors.border.light)};
      border-radius: ${unsafeCSS(components.toolbar.borderRadius)};
      padding: ${unsafeCSS(spacing.sm)} ${unsafeCSS(spacing.lg)};
      box-shadow: ${unsafeCSS(components.toolbar.boxShadow)};
      min-height: ${unsafeCSS(components.toolbar.minHeight)};
      user-select: none;
    }

    @media (prefers-color-scheme: dark) {
      .toolbar {
        background: ${unsafeCSS(colors.background.overlayDark)};
        border-color: ${unsafeCSS(colors.border.dark)};
        color: ${unsafeCSS(colors.text.inverse)};
      }
    }

    .deck-selector {
      background: none;
      border: none;
      padding: ${unsafeCSS(spacing.xs)} ${unsafeCSS(spacing.md)};
      border-radius: ${unsafeCSS(components.button.borderRadius)};
      font-size: ${unsafeCSS(typography.fontSize.sm)};
      font-family: inherit;
      cursor: pointer;
      min-width: 120px;
    }

    .deck-selector:hover {
      background: ${unsafeCSS(colors.interactive.hover)};
    }

    @media (prefers-color-scheme: dark) {
      .deck-selector {
        color: ${unsafeCSS(colors.text.inverse)};
      }
      
      .deck-selector:hover {
        background: ${unsafeCSS(colors.interactive.hoverDark)};
      }
    }

    .nav-button {
      display: flex;
      align-items: center;
      justify-content: center;
      width: ${unsafeCSS(components.button.size.sm)};
      height: ${unsafeCSS(components.button.size.sm)};
      border: none;
      border-radius: ${unsafeCSS(components.button.borderRadius)};
      background: none;
      cursor: pointer;
      transition: background-color 0.2s;
    }

    .nav-button:hover:not(:disabled) {
      background: ${unsafeCSS(colors.interactive.hover)};
    }

    .nav-button:disabled {
      opacity: ${unsafeCSS(colors.interactive.disabled)};
      cursor: not-allowed;
    }

    @media (prefers-color-scheme: dark) {
      .nav-button:hover:not(:disabled) {
        background: ${unsafeCSS(colors.interactive.hoverDark)};
      }
    }

    .nav-button svg {
      width: ${unsafeCSS(spacing.lg)};
      height: ${unsafeCSS(spacing.lg)};
      fill: currentColor;
    }

    .slide-info {
      display: flex;
      flex-direction: column;
      align-items: center;
      min-width: 100px;
      gap: 2px;
    }

    .slide-label {
      font-weight: ${unsafeCSS(typography.fontWeight.medium)};
      max-width: 150px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }

    .slide-counter {
      font-size: ${unsafeCSS(typography.fontSize.xs)};
      opacity: 0.7;
    }

    .divider {
      width: ${unsafeCSS(components.divider.width)};
      height: ${unsafeCSS(components.divider.height)};
      background: ${unsafeCSS(colors.border.medium)};
      margin: 0 ${unsafeCSS(spacing.xs)};
    }

    @media (prefers-color-scheme: dark) {
      .divider {
        background: ${unsafeCSS(colors.border.darkMedium)};
      }
    }

    :host([hidden]) {
      display: none !important;
    }
  `

  connectedCallback() {
    super.connectedCallback()
    
    // Listen for store events
    window.addEventListener('iteration-deck:deck-registered', this.handleStoreUpdate)
    window.addEventListener('iteration-deck:deck-unregistered', this.handleStoreUpdate)
    window.addEventListener('iteration-deck:active-deck-changed', this.handleStoreUpdate)
    window.addEventListener('iteration-deck:slide-changed', this.handleStoreUpdate)
    
    // Setup keyboard shortcuts
    window.addEventListener('keydown', this.handleKeydown)
    
    // Initial state
    this.updateState()
  }

  disconnectedCallback() {
    super.disconnectedCallback()
    window.removeEventListener('iteration-deck:deck-registered', this.handleStoreUpdate)
    window.removeEventListener('iteration-deck:deck-unregistered', this.handleStoreUpdate)
    window.removeEventListener('iteration-deck:active-deck-changed', this.handleStoreUpdate)
    window.removeEventListener('iteration-deck:slide-changed', this.handleStoreUpdate)
    window.removeEventListener('keydown', this.handleKeydown)
  }

  private handleStoreUpdate = () => {
    this.updateState()
  }

  private updateState() {
    this.decks = this.store.getAllDecks()
    this.activeDeckId = this.store.getActiveDeckId()
    this.isVisible = isDevelopment() && this.store.isGlobalToolbarVisible()
  }

  private handleKeydown = (event: KeyboardEvent) => {
    if (!isDevelopment() || !this.isVisible) return
    
    if (event.ctrlKey || event.metaKey) {
      switch (event.key) {
        case 'ArrowLeft':
          event.preventDefault()
          this.store.previousSlide()
          break
        case 'ArrowRight':
          event.preventDefault()
          this.store.nextSlide()
          break
      }
    }
  }

  private handleDeckChange(event: Event) {
    const target = event.target as HTMLSelectElement
    this.store.setActiveDeck(target.value || null)
  }

  private handlePreviousSlide() {
    this.store.previousSlide()
  }

  private handleNextSlide() {
    this.store.nextSlide()
  }

  render() {
    if (!this.isVisible) {
      return html``
    }

    const activeDeck = this.store.getActiveDeck()
    const hasMultipleDecks = this.decks.length > 1
    const currentSlideIndex = activeDeck?.activeSlideIndex ?? 0
    const totalSlides = activeDeck?.slides.length ?? 0
    const currentSlide = activeDeck?.slides[currentSlideIndex]
    const canNavigate = totalSlides > 1

    return html`
      <div class="toolbar" role="toolbar" aria-label="Iteration Deck Controls">
        ${hasMultipleDecks ? html`
          <select 
            class="deck-selector"
            .value="${this.activeDeckId || ''}"
            @change="${this.handleDeckChange}"
            aria-label="Select iteration deck"
          >
            ${this.decks.map(deck => html`
              <option value="${deck.id}">
                ${deck.label || deck.id}
              </option>
            `)}
          </select>
          <div class="divider"></div>
        ` : ''}

        <button
          class="nav-button"
          @click="${this.handlePreviousSlide}"
          ?disabled="${!canNavigate}"
          aria-label="Previous slide"
          title="Previous slide (Ctrl/Cmd + ←)"
        >
          <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M10.7071 2.29289C11.0976 2.68342 11.0976 3.31658 10.7071 3.70711L6.41421 8L10.7071 12.2929C11.0976 12.6834 11.0976 13.3166 10.7071 13.7071C10.3166 14.0976 9.68342 14.0976 9.29289 13.7071L4.29289 8.70711C3.90237 8.31658 3.90237 7.68342 4.29289 7.29289L9.29289 2.29289C9.68342 1.90237 10.3166 1.90237 10.7071 2.29289Z" fill="currentColor" />
          </svg>
        </button>

        <div class="slide-info">
          ${currentSlide ? html`
            <span class="slide-label">${currentSlide.label}</span>
          ` : ''}
          <span class="slide-counter">
            ${currentSlideIndex + 1} / ${totalSlides}
          </span>
        </div>

        <button
          class="nav-button"
          @click="${this.handleNextSlide}"
          ?disabled="${!canNavigate}"
          aria-label="Next slide"
          title="Next slide (Ctrl/Cmd + →)"
        >
          <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M5.29289 2.29289C5.68342 1.90237 6.31658 1.90237 6.70711 2.29289L11.7071 7.29289C12.0976 7.68342 12.0976 8.31658 11.7071 8.70711L6.70711 13.7071C6.31658 14.0976 5.68342 14.0976 5.29289 13.7071C4.90237 13.3166 4.90237 12.6834 5.29289 12.2929L9.58579 8L5.29289 3.70711C4.90237 3.31658 4.90237 2.68342 5.29289 2.29289Z" fill="currentColor" />
          </svg>
        </button>
      </div>
    `
  }
}

// src/react/IterationDeckToolbar.tsx
/**
 * IterationDeckToolbar component
 * 
 * Global toolbar component that provides navigation controls for iteration decks.
 * Uses standard React + Tailwind CSS patterns for maintainability and hot reload.
 */

import React, { useEffect, useState, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { useIterationStore } from './store';


/**
 * Toolbar component props
 */
export interface IterationDeckToolbarProps {
  /** Optional className for the toolbar container */
  className?: string;
}

/**
 * Deck selector dropdown component
 */
const DeckSelector: React.FC<{
  decks: { id: string; label?: string }[];
  selectedDeckId?: string;
  onSelect: (deckId: string) => void;
}> = ({ decks, selectedDeckId, onSelect }) => {
  const selectedDeck = decks.find(d => d.id === selectedDeckId);
  const displayLabel = selectedDeck ? (selectedDeck.label || selectedDeck.id) : 'Select Deck';

  if (decks.length <= 1) return null;

  return (
    <div className="relative flex items-center">
      <select 
        className="absolute top-0 left-0 w-full h-full opacity-0 cursor-pointer z-[2]"
        onChange={(e) => onSelect(e.target.value)}
        value={selectedDeckId || ''}
        aria-label="Select iteration deck"
      >
        {decks.map(deck => (
          <option 
            key={deck.id}
            value={deck.id}
          >
            {deck.label || deck.id}
          </option>
        ))}
      </select>
      
      <div className="flex items-center justify-between h-7 min-w-[120px] gap-3 px-3 bg-white border-2 border-gray-300 dark:bg-gray-800 dark:border-gray-600 rounded-3xl text-sm font-normal leading-3 text-gray-700 dark:text-gray-200 cursor-pointer select-none hover:bg-gray-50 dark:hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400">
        <span className="flex-1 overflow-hidden text-ellipsis whitespace-nowrap">{displayLabel}</span>
        <span className="text-[8px] text-gray-500 dark:text-gray-400 pointer-events-none">▼</span>
      </div>
    </div>
  );
};

/**
 * Slide navigation buttons component
 */
const SlideNavigation: React.FC<{
  onPrevious: () => void;
  onNext: () => void;
  canGoPrevious: boolean;
  canGoNext: boolean;
}> = ({ onPrevious, onNext, canGoPrevious, canGoNext }) => {
  // Base button classes (shared by both buttons)
  const baseButtonClass = "flex items-center justify-center w-8 h-full bg-white dark:bg-gray-800 transition-all duration-150 ease-out text-gray-600 dark:text-gray-300 text-sm cursor-pointer select-none hover:bg-gray-50 hover:text-gray-800 dark:hover:bg-gray-600 dark:hover:text-gray-100 active:bg-gray-100 active:scale-95 dark:active:bg-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-inset dark:focus:ring-blue-400 disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:bg-white disabled:hover:text-gray-600 dark:disabled:hover:bg-gray-700 dark:disabled:hover:text-gray-300 disabled:active:scale-100";

  return (
    <div className="flex items-center rounded-3xl border-2 border-gray-300 dark:border-gray-600 overflow-hidden h-7 bg-gray-200 dark:bg-gray-600">
      <button
        onClick={onPrevious}
        disabled={!canGoPrevious}
        className={`${baseButtonClass} rounded-l-3xl border-r-0`}
        aria-label="Previous slide (Ctrl/Cmd+Alt+[)"
        title="Previous slide (Ctrl/Cmd+Alt+[)"
      >
        <svg width="18" height="12" viewBox="0 0 18 12" fill="currentColor" aria-hidden="true">
          <path d="M7 6l6-4v8l-6-4z" />
        </svg>
      </button>
      <button
        onClick={onNext}
        disabled={!canGoNext}
        className={`${baseButtonClass} rounded-r-3xl border-l-0`}
        aria-label="Next slide (Ctrl/Cmd+Alt+])"
        title="Next slide (Ctrl/Cmd+Alt+])"
      >
        <svg width="18" height="12" viewBox="0 0 18 12" fill="currentColor" aria-hidden="true">
          <path d="M11 6l-6 4V2l6 4z" />
        </svg>
      </button>
    </div>
  );
};

/**
 * Slide info display component
 */
const SlideInfo: React.FC<{
  currentSlide?: { label?: string; index?: number };
  totalSlides: number;
}> = ({ currentSlide, totalSlides }) => {
  // Debug logging
  
  return (
    <div className="flex-1 flex flex-col gap-0 sm:px-2 sm:max-w-4xl lg:max-w-none lg:w-80">
      <span className="text-gray-700 dark:text-gray-200 text-xs font-medium leading-4 overflow-hidden text-ellipsis whitespace-nowrap sm:text-sm">
        {currentSlide?.label || 'No slide selected'}
      </span>
      
      {/* Slide indicators - show debug info when no dots */}
      <div className="flex items-center justify-start gap-1 w-full">
        {totalSlides === 0 ? (
          <span className="text-[8px] text-red-500">No slides (totalSlides: {totalSlides})</span>
        ) : (
          Array.from({ length: totalSlides }, (_, i) => {
            const isActive = i === (currentSlide?.index || 0);
            
            return (
              <div
                key={i}
                className={`w-1 h-1 rounded-full bg-gray-400 transition-opacity duration-200 ${
                  isActive ? 'opacity-90' : 'opacity-50'
                }`}
                title={`Dot ${i} - ${isActive ? 'active' : 'inactive'}`}
              />
            );
          })
        )}
      </div>
    </div>
  );
};

/**
 * Main toolbar component
 */
export const IterationDeckToolbar: React.FC<IterationDeckToolbarProps> = ({ 
  className 
}) => {
  const store = useIterationStore();
  const [isVisible, setIsVisible] = useState(false);

  // Get interactive decks and current selection
  const interactiveDecks = store.getInteractiveDecks().map(id => ({
    id,
    label: store.deckMetadata[id]?.label
  }));

  const selectedDeckId = store.selectedDeckId || interactiveDecks[0]?.id;
  const selectedDeck = store.deckMetadata[selectedDeckId];
  
  // Get current slide info
  const currentSlideId = selectedDeckId ? store.activeDecks[selectedDeckId] : undefined;
  const slideIds = selectedDeck?.slideIds || [];
  const currentSlideIndex = currentSlideId ? slideIds.indexOf(currentSlideId) : 0;
  const totalSlides = slideIds.length;
  

  // Show toolbar if we have interactive decks
  useEffect(() => {
    setIsVisible(interactiveDecks.length > 0);
  }, [interactiveDecks.length]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (!selectedDeckId || !isVisible) return;
      
      const isCmd = event.metaKey || event.ctrlKey;
      const isAlt = event.altKey;
      
      if (isCmd && isAlt) {
        if (event.code === 'BracketLeft') { // Cmd+Alt+[
          event.preventDefault();
          handlePrevious();
        } else if (event.code === 'BracketRight') { // Cmd+Alt+]
          event.preventDefault();
          handleNext();
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [selectedDeckId, isVisible]);

  const handleDeckSelect = useCallback((deckId: string) => {
    store.setSelectedDeck(deckId);
  }, [store]);

  const handlePrevious = useCallback(() => {
    if (!selectedDeckId) return;
    
    const slideIds = store.deckMetadata[selectedDeckId]?.slideIds || [];
    const currentIndex = slideIds.indexOf(store.activeDecks[selectedDeckId] || slideIds[0]);
    const previousIndex = currentIndex <= 0 ? slideIds.length - 1 : currentIndex - 1;
    
    store.setActiveSlide(selectedDeckId, slideIds[previousIndex]);
  }, [selectedDeckId, store]);

  const handleNext = useCallback(() => {
    if (!selectedDeckId) return;
    
    const slideIds = store.deckMetadata[selectedDeckId]?.slideIds || [];
    const currentIndex = slideIds.indexOf(store.activeDecks[selectedDeckId] || slideIds[0]);
    const nextIndex = currentIndex >= slideIds.length - 1 ? 0 : currentIndex + 1;
    
    store.setActiveSlide(selectedDeckId, slideIds[nextIndex]);
  }, [selectedDeckId, store]);

  // Don't render if no interactive decks or in production without enable
  if (!isVisible) return null;

  const toolbarContent = (
    <div className={`fixed bottom-2 left-1/2 -translate-x-1/2 z-[9999] flex items-center min-w-80 sm:min-w-96 sm:h-10 gap-1 px-2 py-1 sm:gap-2 sm:px-1 sm:py-1 sm:bottom-4 lg:p-3 rounded-[40px] backdrop-blur-md shadow-lg font-medium text-sm leading-none text-gray-700 bg-gray-200/80 dark:bg-gray-900/70 dark:text-gray-200 ${className || ''}`}>
      {/* Inner container */}
      <div className="flex items-center gap-2 w-full">
        {/* Deck selector */}
        <DeckSelector
          decks={interactiveDecks}
          selectedDeckId={selectedDeckId}
          onSelect={handleDeckSelect}
        />

        {/* Separator */}
        {interactiveDecks.length > 1 && (
          <div className="w-px h-5 bg-gray-400/60 dark:bg-gray-500/70 sm:h-4" />
        )}

        {/* Navigation controls */}
        <div className="flex items-center gap-0 sm:gap-1">
          <SlideNavigation
            onPrevious={handlePrevious}
            onNext={handleNext}
            canGoPrevious={totalSlides > 1}
            canGoNext={totalSlides > 1}
          />
        </div>

        {/* Separator */}
        <div className="w-px h-5 bg-gray-400/60 dark:bg-gray-500/70 sm:h-4" />

        {/* Slide info */}
        <SlideInfo
          currentSlide={{
            label: selectedDeck?.slideIds?.[currentSlideIndex],
            index: currentSlideIndex
          }}
          totalSlides={totalSlides}
        />
      </div>
    </div>
  );

  // Render in portal at document root
  return createPortal(toolbarContent, document.body);
};

export default IterationDeckToolbar;
