// examples/vue/basic-usage.vue
<template>
  <div class="vue-example">
    <h1>🎛️ Iteration Deck - Vue Integration</h1>
    <p>
      This example demonstrates how to integrate Iteration Deck components 
      with Vue 3 Composition API and TypeScript.
    </p>

    <div class="integration-tip">
      <strong>💡 Vue Integration Tips:</strong>
      <ul>
        <li>Web components work seamlessly with Vue</li>
        <li>Use ref templates for component access</li>
        <li>Reactive state updates automatically</li>
        <li>Event handling works with Vue methods</li>
      </ul>
    </div>

    <!-- Hero Section Variations -->
    <section class="example-section">
      <h2>Hero Section Variations</h2>
      <p>Vue components wrapped in Iteration Deck slides</p>

      <iteration-deck
        id="vue-heroes"
        label="Vue Hero Components"
        prompt="Create 3 Vue hero components with different layouts"
      >
        <iteration-deck-slide
          label="Centered"
          ai-prompt="Bold centered hero with gradient background"
          :confidence="0.92"
          notes="High impact design for landing pages"
        >
          <HeroComponent variant="centered" />
        </iteration-deck-slide>

        <iteration-deck-slide
          label="Split Layout"
          ai-prompt="Content left, visual right, professional look"
          :confidence="0.87"
        >
          <HeroComponent variant="split" />
        </iteration-deck-slide>

        <iteration-deck-slide
          label="Minimal"
          ai-prompt="Clean minimal design with subtle borders"
          :confidence="0.95"
          notes="Best for B2B audiences, converts well"
        >
          <HeroComponent variant="minimal" />
        </iteration-deck-slide>
      </iteration-deck>
    </section>

    <!-- Interactive Button Variations -->
    <section class="example-section">
      <h2>Interactive Button Variations</h2>
      <p>Vue button components with reactive state</p>

      <iteration-deck
        id="vue-buttons"
        label="Vue Button Components"
        prompt="Create accessible Vue button component with style variants"
      >
        <iteration-deck-slide
          label="Primary"
          ai-prompt="Bold primary button, high contrast"
          :confidence="0.95"
        >
          <div class="button-demo">
            <ButtonComponent
              variant="primary"
              @click="handleButtonClick('primary')"
            >
              Get Started
            </ButtonComponent>
            <p class="button-description">
              High contrast, excellent accessibility
            </p>
            <div class="click-counter">
              Clicked {{ clickCounts.primary }} times
            </div>
          </div>
        </iteration-deck-slide>

        <iteration-deck-slide
          label="Outline"
          ai-prompt="Subtle outline style, professional look"
          :confidence="0.87"
        >
          <div class="button-demo">
            <ButtonComponent
              variant="outline"
              @click="handleButtonClick('outline')"
            >
              Get Started
            </ButtonComponent>
            <p class="button-description">
              Subtle, professional appearance
            </p>
            <div class="click-counter">
              Clicked {{ clickCounts.outline }} times
            </div>
          </div>
        </iteration-deck-slide>

        <iteration-deck-slide
          label="Gradient"
          ai-prompt="Eye-catching gradient with depth"
          :confidence="0.92"
          notes="Great for hero sections and key CTAs"
        >
          <div class="button-demo">
            <ButtonComponent
              variant="gradient"
              @click="handleButtonClick('gradient')"
            >
              Get Started
            </ButtonComponent>
            <p class="button-description">
              Visual interest with gradient background
            </p>
            <div class="click-counter">
              Clicked {{ clickCounts.gradient }} times
            </div>
          </div>
        </iteration-deck-slide>
      </iteration-deck>
    </section>

    <!-- Dynamic Form Component -->
    <section class="example-section">
      <h2>Dynamic Form Layouts</h2>
      <p>Reactive Vue forms with different layouts</p>

      <div class="form-controls">
        <label>
          Form Style:
          <select v-model="selectedFormStyle">
            <option value="modern">Modern</option>
            <option value="classic">Classic</option>
            <option value="minimal">Minimal</option>
          </select>
        </label>
        <div class="form-stats">
          Form submissions: {{ formSubmissions }}
        </div>
      </div>

      <iteration-deck
        id="vue-forms"
        label="Vue Form Components"
        prompt="Create responsive Vue form layouts with state management"
      >
        <iteration-deck-slide
          label="Vertical Layout"
          ai-prompt="Stack form fields vertically for mobile-first design"
          :confidence="0.94"
        >
          <FormComponent
            layout="vertical"
            :style-variant="selectedFormStyle"
            @submit="handleFormSubmit"
          />
        </iteration-deck-slide>

        <iteration-deck-slide
          label="Horizontal Layout"
          ai-prompt="Arrange fields horizontally for desktop efficiency"
          :confidence="0.87"
        >
          <FormComponent
            layout="horizontal"
            :style-variant="selectedFormStyle"
            @submit="handleFormSubmit"
          />
        </iteration-deck-slide>

        <iteration-deck-slide
          label="Grid Layout"
          ai-prompt="Use CSS Grid for responsive form design"
          :confidence="0.91"
          notes="Best for complex forms with many fields"
        >
          <FormComponent
            layout="grid"
            :style-variant="selectedFormStyle"
            @submit="handleFormSubmit"
          />
        </iteration-deck-slide>
      </iteration-deck>
    </section>

    <!-- Data Visualization -->
    <section class="example-section">
      <h2>Data Visualization Components</h2>
      <p>Vue components with live reactive data</p>

      <iteration-deck
        id="vue-charts"
        label="Vue Chart Components"
        description="Data visualization with reactive updates"
      >
        <iteration-deck-slide
          label="Simple Chart"
          :confidence="0.89"
        >
          <ChartComponent
            variant="simple"
            :data="chartData"
            @refresh="refreshChartData"
          />
        </iteration-deck-slide>

        <iteration-deck-slide
          label="Detailed Chart"
          :confidence="0.92"
          notes="Includes real-time updates"
        >
          <ChartComponent
            variant="detailed"
            :data="chartData"
            @refresh="refreshChartData"
          />
        </iteration-deck-slide>

        <iteration-deck-slide
          label="Interactive Chart"
          :confidence="0.86"
        >
          <ChartComponent
            variant="interactive"
            :data="chartData"
            @refresh="refreshChartData"
            @datapoint-click="handleDatapointClick"
          />
        </iteration-deck-slide>
      </iteration-deck>
    </section>

    <!-- Vue Integration Guide -->
    <section class="example-section">
      <h2>🔧 Vue Integration Best Practices</h2>
      <div class="best-practices-grid">
        <div class="practice-card practice-card--setup">
          <h4>🎯 Component Setup</h4>
          <ul>
            <li>Import web components in main.js</li>
            <li>Use TypeScript for type safety</li>
            <li>Wrap Vue components in slides</li>
            <li>Event emitters work normally</li>
          </ul>
        </div>

        <div class="practice-card practice-card--reactivity">
          <h4>🚀 Reactivity Features</h4>
          <ul>
            <li>Reactive state updates automatically</li>
            <li>Computed properties for derived data</li>
            <li>Watchers for side effects</li>
            <li>Lifecycle hooks for setup/cleanup</li>
          </ul>
        </div>

        <div class="practice-card practice-card--workflow">
          <h4>👥 Team Workflow</h4>
          <ul>
            <li>Share live Vue prototypes</li>
            <li>Compare component variants</li>
            <li>Track AI generation context</li>
            <li>Present to stakeholders</li>
          </ul>
        </div>
      </div>
    </section>

    <!-- Development vs Production -->
    <section class="example-section">
      <h2>🔧 Development vs Production Behavior</h2>
      <div class="environment-grid">
        <div class="env-card env-card--dev">
          <h4>Development Mode</h4>
          <ul>
            <li>Global toolbar with navigation</li>
            <li>Multi-deck selector dropdown</li>
            <li>Keyboard shortcuts (Ctrl/Cmd + ←/→)</li>
            <li>AI confidence scores visible</li>
            <li>All slides available for comparison</li>
          </ul>
        </div>
        <div class="env-card env-card--prod">
          <h4>Production Mode</h4>
          <ul>
            <li>No toolbar or dev tools</li>
            <li>Only first slide rendered</li>
            <li>Zero overhead</li>
            <li>Clean presentation mode</li>
            <li>Static HTML-like behavior</li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted, onUnmounted } from 'vue'
import { defineCustomElements } from 'iteration-deck/loader'
import HeroComponent from './components/HeroComponent.vue'
import ButtonComponent from './components/ButtonComponent.vue'
import FormComponent from './components/FormComponent.vue'
import ChartComponent from './components/ChartComponent.vue'

// Initialize the web components
defineCustomElements()

// Reactive state
const clickCounts = reactive({
  primary: 0,
  outline: 0,
  gradient: 0,
})

const selectedFormStyle = ref<'modern' | 'classic' | 'minimal'>('modern')
const formSubmissions = ref(0)

const chartData = reactive({
  users: 1234,
  revenue: 45678,
  growth: 12.5,
  lastUpdate: new Date(),
})

// Computed properties
const totalClicks = computed(() => {
  return Object.values(clickCounts).reduce((sum, count) => sum + count, 0)
})

// Methods
const handleButtonClick = (variant: keyof typeof clickCounts) => {
  clickCounts[variant]++
  console.log(`${variant} button clicked! Total clicks: ${totalClicks.value}`)
}

const handleFormSubmit = (formData: any) => {
  formSubmissions.value++
  console.log('Form submitted:', formData)
}

const refreshChartData = () => {
  chartData.users = Math.floor(Math.random() * 10000)
  chartData.revenue = Math.floor(Math.random() * 100000)
  chartData.growth = (Math.random() - 0.5) * 50
  chartData.lastUpdate = new Date()
}

const handleDatapointClick = (datapoint: any) => {
  console.log('Datapoint clicked:', datapoint)
}

// Auto-refresh chart data
let chartInterval: NodeJS.Timeout

onMounted(() => {
  console.log('🎛️ Vue Iteration Deck example loaded')
  
  // Start auto-refresh for chart data
  chartInterval = setInterval(refreshChartData, 5000)
})

onUnmounted(() => {
  if (chartInterval) {
    clearInterval(chartInterval)
  }
})
</script>

<style scoped>
.vue-example {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.6;
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
  background: #f8fafc;
}

.integration-tip {
  background: #f1f5f9;
  padding: 1rem;
  border-radius: 6px;
  margin: 1rem 0;
  font-size: 14px;
  border-left: 4px solid #3b82f6;
}

.integration-tip ul {
  margin: 0.5rem 0 0 0;
  padding-left: 1.25rem;
}

.example-section {
  margin: 3rem 0;
  padding: 2rem;
  background: white;
  border-radius: 12px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.button-demo {
  padding: 2rem;
  text-align: center;
}

.button-description {
  margin-top: 1rem;
  color: #6b7280;
  font-size: 14px;
}

.click-counter {
  margin-top: 0.5rem;
  font-size: 12px;
  color: #3b82f6;
  font-weight: 600;
}

.form-controls {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
  padding: 1rem;
  background: #f9fafb;
  border-radius: 6px;
}

.form-controls label {
  font-size: 14px;
  font-weight: 500;
}

.form-controls select {
  margin-left: 0.5rem;
  padding: 4px 8px;
  border-radius: 4px;
  border: 1px solid #d1d5db;
}

.form-stats {
  font-size: 14px;
  color: #6b7280;
}

.best-practices-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 1.5rem;
  margin-top: 1rem;
}

.practice-card {
  padding: 1.5rem;
  border-radius: 8px;
}

.practice-card--setup {
  background: #f0f9ff;
  border: 1px solid #0ea5e9;
}

.practice-card--setup h4 {
  color: #0369a1;
  margin: 0 0 0.5rem 0;
}

.practice-card--setup ul {
  margin: 0;
  padding-left: 1.25rem;
  color: #075985;
}

.practice-card--reactivity {
  background: #f0fdf4;
  border: 1px solid #22c55e;
}

.practice-card--reactivity h4 {
  color: #166534;
  margin: 0 0 0.5rem 0;
}

.practice-card--reactivity ul {
  margin: 0;
  padding-left: 1.25rem;
  color: #15803d;
}

.practice-card--workflow {
  background: #fef3c7;
  border: 1px solid #f59e0b;
}

.practice-card--workflow h4 {
  color: #92400e;
  margin: 0 0 0.5rem 0;
}

.practice-card--workflow ul {
  margin: 0;
  padding-left: 1.25rem;
  color: #92400e;
}

.environment-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 2rem;
  margin-top: 1rem;
}

.env-card {
  padding: 1.5rem;
  border-radius: 8px;
}

.env-card--dev {
  background: #f0f9ff;
  border: 1px solid #0ea5e9;
}

.env-card--dev h4 {
  margin: 0 0 0.5rem 0;
  color: #0369a1;
}

.env-card--dev ul {
  margin: 0;
  padding-left: 1.25rem;
  color: #075985;
}

.env-card--prod {
  background: #f0fdf4;
  border: 1px solid #22c55e;
}

.env-card--prod h4 {
  margin: 0 0 0.5rem 0;
  color: #166534;
}

.env-card--prod ul {
  margin: 0;
  padding-left: 1.25rem;
  color: #15803d;
}
</style>

// examples/react/basic-usage.tsx
import React, { useEffect } from 'react';
import { defineCustomElements } from 'iteration-deck/loader';

// Initialize the web components
defineCustomElements();

// TypeScript declarations for the custom elements
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'iteration-deck': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        id: string;
        label?: string;
        prompt?: string;
        description?: string;
        'active-index'?: number;
      };
      'iteration-deck-slide': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        label: string;
        'ai-prompt'?: string;
        notes?: string;
        confidence?: number;
      };
    }
  }
}

// Custom button component for examples
interface ButtonProps {
  variant: 'primary' | 'secondary' | 'outline' | 'gradient';
  children: React.ReactNode;
  onClick?: () => void;
}

const Button: React.FC<ButtonProps> = ({ variant, children, onClick }) => {
  const styles = {
    primary: {
      background: '#3b82f6',
      color: 'white',
      border: 'none',
    },
    secondary: {
      background: '#6b7280',
      color: 'white',
      border: 'none',
    },
    outline: {
      background: 'transparent',
      color: '#3b82f6',
      border: '2px solid #3b82f6',
    },
    gradient: {
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      color: 'white',
      border: 'none',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    },
  };

  return (
    <button
      style={{
        ...styles[variant],
        padding: '12px 24px',
        borderRadius: '6px',
        fontSize: '16px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'transform 0.2s',
      }}
      onClick={onClick}
      onMouseEnter={(e) => {
        e.currentTarget.style.transform = 'translateY(-1px)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.transform = 'translateY(0)';
      }}
    >
      {children}
    </button>
  );
};

// Hero section component with different variants
interface HeroProps {
  variant: 'centered' | 'split' | 'minimal';
}

const Hero: React.FC<HeroProps> = ({ variant }) => {
  const variants = {
    centered: (
      <div style={{
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        padding: '3rem 2rem',
        textAlign: 'center',
        borderRadius: '8px',
      }}>
        <h1 style={{ margin: '0 0 1rem 0', fontSize: '2.5rem' }}>
          Transform Your Workflow
        </h1>
        <p style={{ margin: '0 0 2rem 0', fontSize: '1.25rem', opacity: 0.9 }}>
          Powerful tools for modern teams
        </p>
        <Button variant="primary">Start Free Trial</Button>
      </div>
    ),
    split: (
      <div style={{
        background: '#f3f4f6',
        padding: '2rem',
        display: 'flex',
        gap: '2rem',
        borderRadius: '8px',
        alignItems: 'center',
      }}>
        <div style={{ flex: 1 }}>
          <h1 style={{ margin: '0 0 1rem 0', color: '#1f2937' }}>
            Build Amazing Products
          </h1>
          <p style={{ margin: '0 0 2rem 0', color: '#6b7280' }}>
            Split layout balances content with visual elements for better engagement.
          </p>
          <Button variant="primary">Learn More</Button>
        </div>
        <div style={{
          flex: 1,
          height: '200px',
          background: '#e5e7eb',
          borderRadius: '6px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: '#6b7280',
        }}>
          📊 Interactive Demo
        </div>
      </div>
    ),
    minimal: (
      <div style={{
        background: 'white',
        padding: '4rem 2rem',
        textAlign: 'center',
        border: '1px solid #e5e7eb',
        borderRadius: '8px',
      }}>
        <h1 style={{ margin: '0 0 1rem 0', color: '#1f2937', fontWeight: '400' }}>
          Simple. Powerful. Effective.
        </h1>
        <p style={{ margin: '0 0 2rem 0', color: '#6b7280' }}>
          Minimal design that lets your content shine
        </p>
        <Button variant="outline">Get Started</Button>
      </div>
    ),
  };

  return variants[variant];
};

// Product card component
interface ProductCardProps {
  variant: 'standard' | 'compact' | 'featured';
}

const ProductCard: React.FC<ProductCardProps> = ({ variant }) => {
  const variants = {
    standard: (
      <div style={{
        background: 'white',
        borderRadius: '8px',
        overflow: 'hidden',
        boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
        maxWidth: '300px',
      }}>
        <div style={{
          height: '200px',
          background: 'linear-gradient(45deg, #667eea, #764ba2)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: 'white',
          fontSize: '18px',
        }}>
          📱 Product Image
        </div>
        <div style={{ padding: '1.5rem' }}>
          <h3 style={{ margin: '0 0 0.5rem 0' }}>Premium Plan</h3>
          <p style={{ margin: '0 0 1rem 0', color: '#6b7280' }}>
            Everything you need to scale your business
          </p>
          <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#1f2937' }}>
            $29/month
          </div>
        </div>
      </div>
    ),
    compact: (
      <div style={{
        display: 'flex',
        gap: '1rem',
        alignItems: 'center',
        padding: '1.5rem',
        background: 'white',
        borderRadius: '8px',
        boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
      }}>
        <div style={{
          width: '80px',
          height: '80px',
          background: 'linear-gradient(45deg, #667eea, #764ba2)',
          borderRadius: '8px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: 'white',
        }}>
          📱
        </div>
        <div style={{ flex: 1 }}>
          <h3 style={{ margin: '0 0 0.25rem 0' }}>Premium Plan</h3>
          <p style={{ margin: '0 0 0.5rem 0', color: '#6b7280', fontSize: '14px' }}>
            Scale your business
          </p>
          <div style={{ fontSize: '20px', fontWeight: 'bold', color: '#1f2937' }}>
            $29/month
          </div>
        </div>
      </div>
    ),
    featured: (
      <div style={{ maxWidth: '300px', position: 'relative' }}>
        <div style={{
          position: 'absolute',
          top: '-8px',
          right: '-8px',
          background: '#f59e0b',
          color: 'white',
          padding: '4px 12px',
          borderRadius: '12px',
          fontSize: '12px',
          fontWeight: 'bold',
        }}>
          POPULAR
        </div>
        <div style={{
          background: 'white',
          borderRadius: '8px',
          overflow: 'hidden',
          boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
        }}>
          <div style={{
            height: '200px',
            background: 'linear-gradient(45deg, #667eea, #764ba2)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'white',
            fontSize: '18px',
          }}>
            ⭐ Featured
          </div>
          <div style={{ padding: '1.5rem' }}>
            <h3 style={{ margin: '0 0 0.5rem 0' }}>Premium Plan</h3>
            <p style={{ margin: '0 0 1rem 0', color: '#6b7280' }}>
              Most popular choice for growing teams
            </p>
            <div style={{
              fontSize: '24px',
              fontWeight: 'bold',
              color: '#1f2937',
              marginBottom: '1rem',
            }}>
              $29/month
            </div>
            <Button variant="gradient">Choose Plan</Button>
          </div>
        </div>
      </div>
    ),
  };

  return variants[variant];
};

// Main App component
const App: React.FC = () => {
  useEffect(() => {
    console.log('🎛️ React Iteration Deck example loaded');
  }, []);

  return (
    <div style={{
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      lineHeight: 1.6,
      maxWidth: '1200px',
      margin: '0 auto',
      padding: '2rem',
      background: '#f8fafc',
    }}>
      <h1>🎛️ Iteration Deck - React Integration</h1>
      <p>
        This example demonstrates how to integrate Iteration Deck components 
        with React components and TypeScript.
      </p>

      <div style={{
        background: '#f1f5f9',
        padding: '1rem',
        borderRadius: '6px',
        margin: '1rem 0',
        fontSize: '14px',
        borderLeft: '4px solid #3b82f6',
      }}>
        <strong>💡 React Integration Tips:</strong>
        <ul style={{ margin: '0.5rem 0 0 0', paddingLeft: '1.25rem' }}>
          <li>Web components work seamlessly with React</li>
          <li>Use TypeScript declarations for type safety</li>
          <li>Initialize components in your app entry point</li>
          <li>Keyboard shortcuts work automatically</li>
        </ul>
      </div>

      {/* Hero Section Variations */}
      <div style={{
        margin: '3rem 0',
        padding: '2rem',
        background: 'white',
        borderRadius: '12px',
        boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
      }}>
        <h2>Hero Section Variations</h2>
        <p>React components wrapped in Iteration Deck slides</p>

        <iteration-deck
          id="react-heroes"
          label="React Hero Components"
          prompt="Create 3 React hero components with different layouts"
        >
          <iteration-deck-slide
            label="Centered"
            ai-prompt="Bold centered hero with gradient background"
            confidence={0.92}
            notes="High impact design for landing pages"
          >
            <Hero variant="centered" />
          </iteration-deck-slide>

          <iteration-deck-slide
            label="Split Layout"
            ai-prompt="Content left, visual right, professional look"
            confidence={0.87}
          >
            <Hero variant="split" />
          </iteration-deck-slide>

          <iteration-deck-slide
            label="Minimal"
            ai-prompt="Clean minimal design with subtle borders"
            confidence={0.95}
            notes="Best for B2B audiences, converts well"
          >
            <Hero variant="minimal" />
          </iteration-deck-slide>
        </iteration-deck>
      </div>

      {/* Button Variations */}
      <div style={{
        margin: '3rem 0',
        padding: '2rem',
        background: 'white',
        borderRadius: '12px',
        boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
      }}>
        <h2>Button Component Variations</h2>
        <p>Different button styles with React event handlers</p>

        <iteration-deck
          id="react-buttons"
          label="React Button Components"
          prompt="Create accessible React button component with style variants"
        >
          <iteration-deck-slide
            label="Primary"
            ai-prompt="Bold primary button, high contrast"
            confidence={0.95}
          >
            <div style={{ padding: '2rem', textAlign: 'center' }}>
              <Button
                variant="primary"
                onClick={() => alert('Primary button clicked!')}
              >
                Get Started
              </Button>
              <p style={{ marginTop: '1rem', color: '#6b7280', fontSize: '14px' }}>
                High contrast, excellent accessibility
              </p>
            </div>
          </iteration-deck-slide>

          <iteration-deck-slide
            label="Outline"
            ai-prompt="Subtle outline style, professional look"
            confidence={0.87}
          >
            <div style={{ padding: '2rem', textAlign: 'center' }}>
              <Button
                variant="outline"
                onClick={() => alert('Outline button clicked!')}
              >
                Get Started
              </Button>
              <p style={{ marginTop: '1rem', color: '#6b7280', fontSize: '14px' }}>
                Subtle, professional appearance
              </p>
            </div>
          </iteration-deck-slide>

          <iteration-deck-slide
            label="Gradient"
            ai-prompt="Eye-catching gradient with depth"
            confidence={0.92}
            notes="Great for hero sections and key CTAs"
          >
            <div style={{ padding: '2rem', textAlign: 'center' }}>
              <Button
                variant="gradient"
                onClick={() => alert('Gradient button clicked!')}
              >
                Get Started
              </Button>
              <p style={{ marginTop: '1rem', color: '#6b7280', fontSize: '14px' }}>
                Visual interest with gradient background
              </p>
            </div>
          </iteration-deck-slide>
        </iteration-deck>
      </div>

      {/* Product Card Variations */}
      <div style={{
        margin: '3rem 0',
        padding: '2rem',
        background: 'white',
        borderRadius: '12px',
        boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
      }}>
        <h2>Product Card Layouts</h2>
        <p>React component variations for product displays</p>

        <iteration-deck
          id="react-cards"
          label="React Product Cards"
          description="Card layouts for e-commerce and SaaS products"
        >
          <iteration-deck-slide label="Standard" confidence={0.91}>
            <ProductCard variant="standard" />
          </iteration-deck-slide>

          <iteration-deck-slide label="Compact" confidence={0.88}>
            <ProductCard variant="compact" />
          </iteration-deck-slide>

          <iteration-deck-slide
            label="Featured"
            confidence={0.93}
            notes="Popular badge increases conversion"
          >
            <ProductCard variant="featured" />
          </iteration-deck-slide>
        </iteration-deck>
      </div>

      {/* React Best Practices */}
      <div style={{
        margin: '3rem 0',
        padding: '2rem',
        background: 'white',
        borderRadius: '12px',
        boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
      }}>
        <h2>🔧 React Integration Best Practices</h2>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: '1.5rem',
          marginTop: '1rem',
        }}>
          <div style={{
            padding: '1.5rem',
            background: '#f0f9ff',
            border: '1px solid #0ea5e9',
            borderRadius: '8px',
          }}>
            <h4 style={{ margin: '0 0 0.5rem 0', color: '#0369a1' }}>
              🎯 Component Integration
            </h4>
            <ul style={{ margin: '0', paddingLeft: '1.25rem', color: '#075985' }}>
              <li>Initialize web components in your app root</li>
              <li>Use TypeScript declarations for type safety</li>
              <li>Wrap your React components in slides</li>
              <li>Event handlers work normally</li>
            </ul>
          </div>

          <div style={{
            padding: '1.5rem',
            background: '#f0fdf4',
            border: '1px solid #22c55e',
            borderRadius: '8px',
          }}>
            <h4 style={{ margin: '0 0 0.5rem 0', color: '#166534' }}>
              🚀 Performance Tips
            </h4>
            <ul style={{ margin: '0', paddingLeft: '1.25rem', color: '#15803d' }}>
              <li>Lazy load heavy components</li>
              <li>Use React.memo for optimization</li>
              <li>Leverage web component lifecycle</li>
              <li>Production builds hide dev tools</li>
            </ul>
          </div>

          <div style={{
            padding: '1.5rem',
            background: '#fef3c7',
            border: '1px solid #f59e0b',
            borderRadius: '8px',
          }}>
            <h4 style={{ margin: '0 0 0.5rem 0', color: '#92400e' }}>
              👥 Team Workflow
            </h4>
            <ul style={{ margin: '0', paddingLeft: '1.25rem', color: '#92400e' }}>
              <li>Share live React prototypes</li>
              <li>Compare component variants</li>
              <li>Track AI generation context</li>
              <li>Present to stakeholders</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default App;
